#### Import Library

In [30]:
import numpy as np 

#### create array

In [32]:
# create from list
a = np.array([2, 3, 4])
print(a)

b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)

[2 3 4]


In [24]:
# create 

[   1    9   16 3136]
[1.         1.73205081 2.         7.48331477]


In [29]:
a = np.
a


array([1, 3, 5, 7])