In [ ]:
import numpy as np 

In [21]:
a = np.array((1,3,4,56))

In [24]:
b = a*a
print(b)
c = np.sqrt(a)
print(c)

[   1    9   16 3136]
[1.         1.73205081 2.         7.48331477]


In [29]:
a = np.
a


array([1, 3, 5, 7])